package:
  name: vedastro
  version: "0.21"

source:
  git_rev: 0.2
  git_url: https://github.com/VedAstro/VedAstro.Python.git

requirements:
  build:
    - python
    - setuptools
    - pip
    - git
  run:

    - dotnet=7.0.102
    - pythonnet=3.0.1

about:
  home: https://github.com/VedAstro/VedAstro.Python
  license: MIT
  license_file: LICENSE
  summary: A Python wrapper for VedAstro. Vedic Astrology Calculation libray
