package:
  name: vedastro
  version: 1.23.10
source:
  git_rev:0.1
  git_url:https://github.com/VedAstro/VedAstro.Python.git
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
requirements:
  host:
    - python >=3.9,<3.12
    - pip
  run:
    - python >=3.9,<3.12
    - packaging
    - colorama
    - requests
    - pythonnet 3.0.2
    - pycparser
about:
  home: https://github.com/VedAstro/VedAstro
  license: MIT
  license_family: MIT
  summary: An open source Python library for advanced astronomical calculations like planet longitude, house sign, shadbala, etc...
  description: An open source Python library for advanced astronomical calculations like planet longitude, house sign, shadbala, etc...
  doc_url: https://github.com/VedAstro/VedAstro
  dev_url: https://github.com/VedAstro/VedAstro
extra:
  recipe-maintainers:
    - vedastro
