package:
  name: vedastro
  version: "0.22"

source:
  git_rev: 0.2
  git_url: https://github.com/VedAstro/VedAstro.Python.git

requirements:
  build:
    - python
    - setuptools
    - pip
    - wheel

  host:
    - python

  run:
    - pythonnet=3.0.1
    - dotnet=7.0.102


about:
  home: https://github.com/VedAstro/VedAstro.Python
  license: MIT
