package:
   name:vedastro
   version:"7.0"

source:
  git_rev:0.1
  git_url:https://github.com/VedAstro/VedAstro.Python.git

requirements:
  build:

   - dotnet
   - pythonnet

run:
  - python

test:
  imports:vedastro
    -

about:
  home:https://github.com/VedAstro/VedAstro.Python
  license:MIT
